# Ensure PRs can be successfully built
# The build process also includes linting

name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      NEXT_PUBLIC_GA_ID: mock-ga-id
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - uses: oven-sh/setup-bun@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: bun install
      - run: npm ci --include dev
      - run: npm run test
      - run: npm run build
