# Ensure PRs meet linting requirements and can be successfully built

name: Validate

on:
  pull_request:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  lint-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm run lint
      - run: npm ci --production-only --no-audit
      - run: npm run build
